version: "3.8"

networks:
  corp:
    driver: bridge

services:
  nextjs13-client:
    container_name: nextjs13-client
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: "production"
        BUILD_FLAG: ""
    image: marocdevelop/nextjs-docker:v2
    ports:
      - 3000:3000
    environment:
      NODE_ENV: "production"
      PORT: 3000
      TAG: "name-of-branche"
    networks:
      - corp
    restart: on-failure
