import Link from "next/link";
import "../globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <ul>
          <li>
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/user">User</Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
